// Code generated by internal/hexe/gen/examples; DO NOT EDIT.

package main

//go:generate go run ../internal/hexe/gen/examples

var examples = []func(){findPathBfsExample, reflectExample, traceToExample, fieldOfViewExample,

	lineToExample, movementRangeExample, plotExample, diagonalNeighborsExample,

	instantiationExample,

	mathFunctionsExample, neighborsExample,
	rotateExample,

	floodFillExample, ringExample, setsExample}

func main() {
	for _, example := range examples {
		example()
	}
}
