// Code generated by internal/hexe/gen/examples; DO NOT EDIT.

package main

//go:generate go run ../internal/hexe/gen/examples

var examples = []func(){ringExample, movementRangeExample, plotExample, reflectExample,

	setsExample,

	traceToExample, diagonalNeighborsExample, fieldOfViewExample,

	findPathBfsExample,

	instantiationExample,
	neighborsExample, floodFillExample,
	lineToExample, mathFunctionsExample, rotateExample}

func main() {
	for _, example := range examples {
		example()
	}
}
