// Code generated by internal/hexe/gen/examples; DO NOT EDIT.

package main

//go:generate go run ../internal/hexe/gen/examples

var examples = []func(){plotExample, fieldOfViewExample, mathFunctionsExample, neighborsExample,

	ringExample, rotateExample, movementRangeExample, setsExample,

	floodFillExample, instantiationExample,

	reflectExample, traceToExample, diagonalNeighborsExample, findPathBfsExample, lineToExample}

func main() {
	for _, example := range examples {
		example()
	}
}
